//例外処理エラー
class Example_16_1 {
	public static void main(String[] args) {
		int[] data = {10, 20, 30};
		data[5] = 50;
		
		System.out.println("data[5]に代入しました。");
	}
}
